name: dart_auth_server
description: A basic auth server with shelf package
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.6.2
  get_it: ^7.2.0
  random_string: ^2.3.1
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
